#!/bin/bash
BRANCH=$(git rev-parse --abbrev-ref HEAD)
REGEX="^(feature)\/[a-z0-9._-]+$"

if ! [[ $BRANCH =~ $REGEX ]]; then
  echo "Seu commit foi rejeitado pois não segue aos padrões definidos"
  echo "Exemplo de nome válido: 'feature/nova-funcionalidade'"
  exit 1
fi
